server:
  port: 8080

spring:
  profiles:
    active: dev
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.solrdemo.entity
  configuration:
    map-underscore-to-camel-case: true